ALL_CARS = [
"B_MRAP_01_F",
"B_MRAP_01_gmg_F",
"B_MRAP_01_hmg_F",
"O_MRAP_02_F",
"O_MRAP_02_hmg_F",
"O_MRAP_02_gmg_F",
"C_Offroad_01_F",
"C_Offroad_01_repair_F",
"B_G_Offroad_01_repair_F",
"O_G_Offroad_01_repair_F",
"I_G_Offroad_01_repair_F",
"I_G_Offroad_01_F",
"I_G_Offroad_01_AT_F",
"I_G_Offroad_01_armed_F",
"B_G_Offroad_01_F",
"O_G_Offroad_01_F",
"B_G_Offroad_01_armed_F",
"O_G_Offroad_01_armed_F",
"B_G_Offroad_01_AT_F",
"O_G_Offroad_01_AT_F",
"C_Quadbike_01_F",
"B_Quadbike_01_F",
"O_Quadbike_01_F",
"I_Quadbike_01_F",
"I_G_Quadbike_01_F",
"B_G_Quadbike_01_F",
"O_G_Quadbike_01_F",
"I_MRAP_03_F",
"I_MRAP_03_hmg_F",
"I_MRAP_03_gmg_F",
"B_Truck_01_transport_F",
"B_Truck_01_covered_F",
"O_Truck_02_covered_F",
"O_Truck_02_transport_F",
"I_Truck_02_covered_F",
"I_Truck_02_transport_F",
"C_Truck_02_covered_F",
"C_Truck_02_transport_F",
"C_Hatchback_01_F",
"C_Hatchback_01_sport_F",
"C_SUV_01_F",
"B_Truck_01_mover_F",
"B_Truck_01_box_F",
"B_Truck_01_Repair_F",
"B_Truck_01_ammo_F",
"B_Truck_01_fuel_F",
"B_Truck_01_medical_F",
"O_Truck_02_box_F",
"O_Truck_02_medical_F",
"O_Truck_02_Ammo_F",
"O_Truck_02_fuel_F",
"I_Truck_02_box_F",
"I_Truck_02_medical_F",
"I_Truck_02_fuel_F",
"I_Truck_02_MRL_F",
"C_Truck_02_fuel_F",
"C_Truck_02_box_F",
"C_Van_01_transport_F",
"I_G_Van_01_transport_F",
"C_Van_01_box_F",
"C_Van_01_fuel_F",
"I_G_Van_01_fuel_F",
"B_G_Van_01_transport_F",
"O_G_Van_01_transport_F",
"B_G_Van_01_fuel_F",
"O_G_Van_01_fuel_F",
"B_APC_Wheeled_01_cannon_F",
"O_APC_Wheeled_02_rcws_v2_F",
"I_APC_Wheeled_03_cannon_F",
"B_UGV_01_F",
"O_UGV_01_F",
"I_UGV_01_F",
"B_UGV_01_rcws_F",
"O_UGV_01_rcws_F",
"I_UGV_01_rcws_F",
"O_Truck_03_transport_F",
"O_Truck_03_covered_F",
"O_Truck_03_repair_F",
"O_Truck_03_ammo_F",
"O_Truck_03_fuel_F",
"O_Truck_03_medical_F",
"O_Truck_03_device_F",
"TowingTractor",
"C_Kart_01_F",
"C_Kart_01_Fuel_F",
"C_Kart_01_Blu_F",
"C_Kart_01_Red_F",
"C_Kart_01_Vrana_F",
"B_T_LSV_01_armed_F",
"B_T_LSV_01_AT_F",
"B_T_LSV_01_unarmed_F",
"B_LSV_01_armed_F",
"B_LSV_01_AT_F",
"B_LSV_01_unarmed_F",
"B_CTRG_LSV_01_light_F",
"O_T_LSV_02_armed_F",
"O_T_LSV_02_unarmed_F",
"O_T_LSV_02_AT_F",
"O_LSV_02_armed_F",
"O_LSV_02_unarmed_F",
"O_LSV_02_AT_F",
"B_T_MRAP_01_F",
"B_T_MRAP_01_gmg_F",
"B_T_MRAP_01_hmg_F",
"O_T_MRAP_02_ghex_F",
"O_T_MRAP_02_hmg_ghex_F",
"O_T_MRAP_02_gmg_ghex_F",
"B_GEN_Offroad_01_gen_F",
"C_Offroad_02_unarmed_F",
"I_C_Offroad_02_unarmed_F",
"I_C_Offroad_02_LMG_F",
"I_C_Offroad_02_AT_F",
"O_T_Quadbike_01_ghex_F",
"B_T_Quadbike_01_F",
"B_T_Truck_01_mover_F",
"B_T_Truck_01_ammo_F",
"B_T_Truck_01_box_F",
"B_T_Truck_01_fuel_F",
"B_T_Truck_01_medical_F",
"B_T_Truck_01_Repair_F",
"B_T_Truck_01_transport_F",
"B_T_Truck_01_covered_F",
"O_T_Truck_03_transport_ghex_F",
"O_T_Truck_03_covered_ghex_F",
"O_T_Truck_03_repair_ghex_F",
"O_T_Truck_03_ammo_ghex_F",
"O_T_Truck_03_fuel_ghex_F",
"O_T_Truck_03_medical_ghex_F",
"O_T_Truck_03_device_ghex_F",
"O_T_UGV_01_ghex_F",
"O_T_UGV_01_rcws_ghex_F",
"I_C_Van_01_transport_F",
"BRDM2_HQ_CHDKZ",
"Exile_Car_BRDM2_HQ",
"Exile_Car_BTR40_MG_Green",
"Exile_Car_BTR40_MG_Camo",
"Exile_Car_BTR40_Green",
"Exile_Car_BTR40_Camo",
"Golf_Civ_Base",
"Exile_Car_Golf_Red",
"Exile_Car_Golf_Black",
"Exile_Car_Hatchback_Beige",
"Exile_Car_Hatchback_Green",
"Exile_Car_Hatchback_Blue",
"Exile_Car_Hatchback_BlueCustom",
"Exile_Car_Hatchback_BeigeCustom",
"Exile_Car_Hatchback_Yellow",
"Exile_Car_Hatchback_Grey",
"Exile_Car_Hatchback_Black",
"Exile_Car_Hatchback_Dark",
"Exile_Car_Hatchback_Rusty1",
"Exile_Car_Hatchback_Rusty2",
"Exile_Car_Hatchback_Rusty3",
"Exile_Car_Hatchback_Sport_Red",
"Exile_Car_Hatchback_Sport_Blue",
"Exile_Car_Hatchback_Sport_Orange",
"Exile_Car_Hatchback_Sport_White",
"Exile_Car_Hatchback_Sport_Beige",
"Exile_Car_Hatchback_Sport_Green",
"Exile_Car_Hatchback_Sport_Admin",
"Exile_Car_HEMMT",
"HMMWV_M134",
"Exile_Car_HMMWV_M134_Green",
"Exile_Car_HMMWV_M134_Desert",
"HMMWV_M2",
"Exile_Car_HMMWV_M2_Green",
"Exile_Car_HMMWV_M2_Desert",
"HMMWV_MEV",
"Exile_Car_HMMWV_MEV_Green",
"Exile_Car_HMMWV_MEV_Desert",
"HMMWV_UNA",
"Exile_Car_HMMWV_UNA_Green",
"Exile_Car_HMMWV_UNA_Desert",
"Exile_Car_Hunter",
"Exile_Car_Ifrit",
"Ikarus_Civ_02",
"Exile_Car_Ikarus_Blue",
"Exile_Car_Ikarus_Red",
"Exile_Car_Ikarus_Party",
"Exile_Car_Kart_BluKing",
"Exile_Car_Kart_RedStone",
"Exile_Car_Kart_Vrana",
"Exile_Car_Kart_Green",
"Exile_Car_Kart_Blue",
"Exile_Car_Kart_Orange",
"Exile_Car_Kart_White",
"Exile_Car_Kart_Yellow",
"Exile_Car_Kart_Black",
"Exile_Car_Lada_Green",
"Exile_Car_Lada_Taxi",
"Exile_Car_Lada_Red",
"Exile_Car_Lada_White",
"Exile_Car_Lada_Hipster",
"Landrover_Civ_02",
"Exile_Car_LandRover_Red",
"Exile_Car_LandRover_Urban",
"Exile_Car_LandRover_Green",
"Exile_Car_LandRover_Sand",
"Exile_Car_LandRover_Desert",
"LR_Ambulance_Base",
"Exile_Car_LandRover_Ambulance_Green",
"Exile_Car_LandRover_Ambulance_Desert",
"Exile_Car_LandRover_Ambulance_Sand",
"Exile_Car_MB4WD",
"Exile_Car_MB4WDOpen",
"Octavia_Civ_01",
"Exile_Car_Octavius_White",
"Exile_Car_Octavius_Black",
"Exile_Car_Offroad_Red",
"Exile_Car_Offroad_Beige",
"Exile_Car_Offroad_White",
"Exile_Car_Offroad_Blue",
"Exile_Car_Offroad_DarkRed",
"Exile_Car_Offroad_BlueCustom",
"Exile_Car_Offroad_Guerilla01",
"Exile_Car_Offroad_Guerilla02",
"Exile_Car_Offroad_Guerilla03",
"Exile_Car_Offroad_Guerilla04",
"Exile_Car_Offroad_Guerilla05",
"Exile_Car_Offroad_Guerilla06",
"Exile_Car_Offroad_Guerilla07",
"Exile_Car_Offroad_Guerilla08",
"Exile_Car_Offroad_Guerilla09",
"Exile_Car_Offroad_Guerilla10",
"Exile_Car_Offroad_Guerilla11",
"Exile_Car_Offroad_Guerilla12",
"Exile_Car_Offroad_Rusty1",
"Exile_Car_Offroad_Rusty2",
"Exile_Car_Offroad_Rusty3",
"Exile_Car_Offroad_Armed_Guerilla01",
"Exile_Car_Offroad_Armed_Guerilla02",
"Exile_Car_Offroad_Armed_Guerilla03",
"Exile_Car_Offroad_Armed_Guerilla04",
"Exile_Car_Offroad_Armed_Guerilla05",
"Exile_Car_Offroad_Armed_Guerilla06",
"Exile_Car_Offroad_Armed_Guerilla07",
"Exile_Car_Offroad_Armed_Guerilla08",
"Exile_Car_Offroad_Armed_Guerilla09",
"Exile_Car_Offroad_Armed_Guerilla10",
"Exile_Car_Offroad_Armed_Guerilla11",
"Exile_Car_Offroad_Armed_Guerilla12",
"Exile_Car_Offroad_Repair_Civillian",
"Exile_Car_Offroad_Repair_Red",
"Exile_Car_Offroad_Repair_Beige",
"Exile_Car_Offroad_Repair_White",
"Exile_Car_Offroad_Repair_Blue",
"Exile_Car_Offroad_Repair_DarkRed",
"Exile_Car_Offroad_Repair_BlueCustom",
"Exile_Car_Offroad_Repair_Guerilla01",
"Exile_Car_Offroad_Repair_Guerilla02",
"Exile_Car_Offroad_Repair_Guerilla03",
"Exile_Car_Offroad_Repair_Guerilla04",
"Exile_Car_Offroad_Repair_Guerilla05",
"Exile_Car_Offroad_Repair_Guerilla06",
"Exile_Car_Offroad_Repair_Guerilla07",
"Exile_Car_Offroad_Repair_Guerilla08",
"Exile_Car_Offroad_Repair_Guerilla09",
"Exile_Car_Offroad_Repair_Guerilla10",
"Exile_Car_Offroad_Repair_Guerilla11",
"Exile_Car_Offroad_Repair_Guerilla12",
"TractorOld",
"Exile_Car_OldTractor_Red",
"Exile_Car_ProwlerLight",
"Exile_Car_ProwlerUnarmed",
"Exile_Car_QilinUnarmed",
"Exile_Car_Strider",
"Exile_Car_SUV_Red",
"Exile_Car_SUV_Black",
"Exile_Car_SUV_Grey",
"Exile_Car_SUV_Orange",
"Exile_Car_SUV_Rusty1",
"Exile_Car_SUV_Rusty2",
"Exile_Car_SUV_Rusty3",
"SUV_Base",
"Exile_Car_SUVXL_Black",
"SUV_armored_Base",
"Exile_Car_SUV_Armed_Black",
"Exile_Car_Tempest",
"Exile_Car_TowTractor_White",
"Tractor_Base",
"Exile_Car_Tractor_Red",
"UAZ_Base",
"Exile_Car_UAZ_Green",
"UAZ_Open_Base",
"Exile_Car_UAZ_Open_Green",
"Ural_RU",
"Exile_Car_Ural_Covered_Blue",
"Exile_Car_Ural_Covered_Yellow",
"Exile_Car_Ural_Covered_Worker",
"Exile_Car_Ural_Covered_Military",
"Ural_Open_RU",
"Exile_Car_Ural_Open_Blue",
"Exile_Car_Ural_Open_Yellow",
"Exile_Car_Ural_Open_Worker",
"Exile_Car_Ural_Open_Military",
"V3S_Base_EP1",
"Exile_Car_V3S_Covered",
"V3S_base",
"Exile_Car_V3S_Open",
"Exile_Car_Van_Black",
"Exile_Car_Van_White",
"Exile_Car_Van_Red",
"Exile_Car_Van_Guerilla01",
"Exile_Car_Van_Guerilla02",
"Exile_Car_Van_Guerilla03",
"Exile_Car_Van_Guerilla04",
"Exile_Car_Van_Guerilla05",
"Exile_Car_Van_Guerilla06",
"Exile_Car_Van_Guerilla07",
"Exile_Car_Van_Guerilla08",
"Exile_Car_Van_Box_Black",
"Exile_Car_Van_Box_White",
"Exile_Car_Van_Box_Red",
"Exile_Car_Van_Box_Guerilla01",
"Exile_Car_Van_Box_Guerilla02",
"Exile_Car_Van_Box_Guerilla03",
"Exile_Car_Van_Box_Guerilla04",
"Exile_Car_Van_Box_Guerilla05",
"Exile_Car_Van_Box_Guerilla06",
"Exile_Car_Van_Box_Guerilla07",
"Exile_Car_Van_Box_Guerilla08",
"Exile_Car_Van_Fuel_Black",
"Exile_Car_Van_Fuel_White",
"Exile_Car_Van_Fuel_Red",
"Exile_Car_Van_Fuel_Guerilla01",
"Exile_Car_Van_Fuel_Guerilla02",
"Exile_Car_Van_Fuel_Guerilla03",
"Exile_Car_Volha_Blue",
"Exile_Car_Volha_White",
"Exile_Car_Volha_Black",
"Exile_Car_Zamak",
"Exile_Bike_QuadBike_Black",
"Exile_Bike_QuadBike_Blue",
"Exile_Bike_QuadBike_Red",
"Exile_Bike_QuadBike_White",
"Exile_Bike_QuadBike_Nato",
"Exile_Bike_QuadBike_Csat",
"Exile_Bike_QuadBike_Fia",
"Exile_Bike_QuadBike_Guerilla01",
"Exile_Bike_QuadBike_Guerilla02",
"BTR40_MG_TK_GUE_EP1",
"BTR40_TK_GUE_EP1",
"BTR40_MG_TK_INS_EP1",
"BTR40_TK_INS_EP1",
"volha_Civ_01",
"volha_Civ_02",
"volha_Civ_03",
"HMMWV_M2_GPK_Base",
"HMMWV_M2_GPK_1",
"HMMWV_M2_des",
"HMMWV_M134_des",
"HMMWV_UNA_des",
"HMMWV_MEV_des",
"Ikarus_Base",
"Ikarus_Govnodav_01",
"Ikarus_Govnodav_02",
"Lada_Civ_01",
"Lada_Civ_02",
"Lada_Civ_03",
"Lada_Civ_04",
"Lada_Militia",
"Landrover_Des",
"Landrover_Civ_01",
"Landrover_Civ_01_Urban1",
"Landrover_Civ_03",
"LR_Ambulance_01",
"LR_Ambulance_02",
"LR_MG_Base",
"Octavia_Civ_03",
"Octavia_Civ_04",
"Octavia_Civ_05",
"SUV_civ_01",
"SUV_civ_02",
"SUV_civ_03",
"SUV_civ_04",
"UAZ_Armed_Base",
"UAZ_MG_Base",
"UAZ_AGS30_Base",
"Ural_Open_Base",
"Ural_Civ_01",
"Ural_Civ_02",
"Ural_Civ_03",
"Ural_Open_Civ_01",
"Ural_Open_Civ_02",
"Ural_Open_Civ_03",
"Golf_Civ_Black",
"Golf_Civ_pink",
"B_T_APC_Wheeled_01_cannon_F",
"O_T_APC_Wheeled_02_rcws_v2_ghex_F",
"C_IDAP_Offroad_01_F",
"C_IDAP_Offroad_02_unarmed_F",
"C_IDAP_Truck_02_F",
"C_IDAP_Truck_02_transport_F",
"C_IDAP_Truck_02_water_F",
"C_IDAP_UGV_01_F",
"C_Van_02_transport_F",
"C_IDAP_Van_02_transport_F",
"I_G_Van_02_transport_F",
"B_G_Van_02_transport_F",
"B_GEN_Van_02_transport_F",
"O_G_Van_02_transport_F",
"I_C_Van_02_transport_F",
"C_Van_02_vehicle_F",
"C_IDAP_Van_02_vehicle_F",
"I_G_Van_02_vehicle_F",
"B_G_Van_02_vehicle_F",
"B_GEN_Van_02_vehicle_F",
"O_G_Van_02_vehicle_F",
"I_C_Van_02_vehicle_F",
"C_Van_02_medevac_F",
"C_IDAP_Van_02_medevac_F",
"C_Van_02_service_F",
"B_AFV_Wheeled_01_cannon_F",
"B_T_AFV_Wheeled_01_cannon_F",
"B_AFV_Wheeled_01_up_cannon_F",
"B_T_AFV_Wheeled_01_up_cannon_F",
"I_LT_01_cannon_F"
];
R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow + ALL_CARS;


R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
    //Larger Vehicles
	"BRDM2_HQ_Base",
	"BTR40_MG_base_EP1",
	"Landrover_civ",
	"Offroad_02_base_F",
	"Offroad_01_unarmed_base_F",
	"Offroad_01_repair_base_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"MRAP_03_base_F",
	"SUV_01_base_F",
	"SUV_armored_Base",
	"SUV_Base",
	"UAZ_Base",
	"HMMWV_Base",
	
	//Trucks
	"Truck_F",	
	"MRAP_01_base_F",
	"MRAP_02_base_F",		
            
    //Armed
    "Offroad_01_military_base_F",
	          
    //Boats
	"Boat_Transport_02_base_F",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F"
];
R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed + ALL_CARS;
R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
    //Cars
    "Hatchback_01_base_F",
	"Lada_Base",
	"Octavia_Base",	
	"volha_Base",
    
    //Larger Vehicles
	"BRDM2_HQ_Base",
	"BTR40_MG_base_EP1",
	"Landrover_civ",
	"Offroad_02_base_F",
	"Offroad_01_unarmed_base_F",
	"Offroad_01_repair_base_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"MRAP_03_base_F",
	"SUV_01_base_F",
	"SUV_armored_Base",
	"SUV_Base",
	"UAZ_Base",
	"HMMWV_Base",
	
	//Trucks
	"Truck_F",	
	"MRAP_01_base_F",
	"MRAP_02_base_F",		
            
    //Armed
    "Offroad_01_military_base_F",
	          
    //Boats
	"Boat_Transport_02_base_F",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F"
                        
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
    
];
R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted + ALL_CARS;
R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
    //Cars
    "Hatchback_01_base_F",
	"Lada_Base",
	"Octavia_Base",	
	"volha_Base",
    
    //Larger Vehicles
	"BRDM2_HQ_Base",
	"BTR40_MG_base_EP1",
	"Landrover_civ",
	"Offroad_02_base_F",
	"Offroad_01_unarmed_base_F",
	"Offroad_01_repair_base_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"MRAP_03_base_F",
	"SUV_01_base_F",
	"SUV_armored_Base",
	"SUV_Base",
	"UAZ_Base",
	"HMMWV_Base",
	
	//Trucks
	"Truck_F",	
	"MRAP_01_base_F",
	"MRAP_02_base_F",		
            
    //Armed
    "Offroad_01_military_base_F",
	"Tank_F",
	
	          
    //Boats
	"Boat_Transport_02_base_F",
	"SDV_01_base_F",
	"Boat_Civil_01_base_F"             
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
    //Cars
    ["Hatchback_01_base_F", 10],
	["Lada_Base", 10],
	["Octavia_Base", 10],	
	["volha_Base", 10],
    
    //Larger Vehicles
	["BRDM2_HQ_Base", 25],
	["BTR40_MG_base_EP1", 25],
	["Landrover_civ", 25],
	["Offroad_02_base_F", 25],
	["Offroad_01_unarmed_base_F", 25],
	["Offroad_01_repair_base_F", 25],
	["LSV_01_base_F", 50],
	["LSV_02_base_F", 50],
	["MRAP_03_base_F", 50],
	["SUV_01_base_F", 25],
	["SUV_armored_Base", 25],
	["SUV_Base", 25],
	["UAZ_Base", 25],
	["HMMWV_Base", 25],
	["MRAP_01_base_F", 50],
	["MRAP_02_base_F", 50],
	
	//Trucks
	["Truck_F", 100],
	["I_Truck_02_ammo_F",100],
            
    //Armed
    ["Offroad_01_military_base_F", 25],
	["I_LT_01_cannon_F",50],
	["B_APC_Wheeled_01_cannon_F",50],
	          
    //Boats
	["Boat_Transport_02_base_F", 25],
	["SDV_01_base_F", 25],
	["Boat_Civil_01_base_F", 25]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
    ["Quadbike_01_base_F", 25],
    ["Bicycle", 10],
	["Golf_Base", 25],   
    ["Kart_01_Base_F", 25],
    ["Tractor_Base", 25],
	["Rubber_duck_base_F", 25],   
    ["TowingTractor", 25]
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
    "Bicycle"
];